# Generated by Django 2.2.3 on 2019-09-16 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_id', models.SmallIntegerField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('base_value', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BonusTerritory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Bonus')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='FogLevel',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number_of_turns', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.SmallIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.SmallIntegerField()),
                ('armies', models.SmallIntegerField(blank=True, null=True)),
                ('card_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStateType',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('is_multi_day', models.BooleanField(default=True)),
                ('is_multi_attack', models.BooleanField(default=False)),
                ('allow_percentage_attacks', models.BooleanField(default=True)),
                ('allow_attack_only', models.BooleanField(default=True)),
                ('allow_transfer_only', models.BooleanField(default=True)),
                ('is_cycle_move_order', models.BooleanField(default=True)),
                ('is_booted_to_ai', models.BooleanField(default=False)),
                ('is_surrender_to_ai', models.BooleanField(default=False)),
                ('times_return_from_ai', models.SmallIntegerField(default=2)),
                ('is_manual_distribution', models.BooleanField(default=True)),
                ('distribution_mode', models.SmallIntegerField(default=-1)),
                ('territory_limit', models.IntegerField()),
                ('initial_armies', models.IntegerField(default=4)),
                ('out_distribution_neutrals', models.IntegerField(default=2)),
                ('in_distribution_neutrals', models.IntegerField(default=4)),
                ('wasteland_count', models.IntegerField()),
                ('wasteland_size', models.IntegerField(default=10)),
                ('is_commerce', models.BooleanField(default=False)),
                ('has_commanders', models.BooleanField(default=False)),
                ('is_one_army_stand_guard', models.BooleanField(default=True)),
                ('base_income', models.IntegerField(default=5)),
                ('luck_modifier', models.FloatField(default=0.0)),
                ('is_straight_round', models.BooleanField(default=True)),
                ('bonus_army_per', models.SmallIntegerField(blank=True, null=True)),
                ('army_cap', models.SmallIntegerField(blank=True, null=True)),
                ('offensive_kill_rate', models.SmallIntegerField(default=60)),
                ('defensive_kill_rate', models.SmallIntegerField(default=70)),
                ('is_local_deployment', models.BooleanField(default=False)),
                ('is_no_split', models.BooleanField(default=False)),
                ('max_cards', models.SmallIntegerField()),
                ('card_pieces_per_turn', models.SmallIntegerField()),
                ('card_playing_visible', models.BooleanField(default=False)),
                ('card_visible', models.BooleanField(default=False)),
                ('uses_mods', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryClaim',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game_analysis.Order')),
                ('attack_transfer', models.CharField(default='AttackTransfer', max_length=15)),
                ('is_attack_teammates', models.BooleanField(default=False)),
                ('is_attack_by_percent', models.BooleanField(default=False)),
                ('is_attack', models.BooleanField(default=False)),
                ('is_successful', models.BooleanField()),
                ('attack_size', models.SmallIntegerField(blank=True, null=True)),
                ('attacking_armies_killed', models.SmallIntegerField(blank=True, null=True)),
                ('defending_armies_killed', models.SmallIntegerField(blank=True, null=True)),
                ('offense_luck', models.FloatField(blank=True, null=True)),
                ('defense_luck', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.SmallIntegerField()),
                ('commit_date_time', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Game')),
            ],
            options={
                'unique_together': {('game', 'turn_number')},
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_id', models.SmallIntegerField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('bonuses', models.ManyToManyField(through='game_analysis.BonusTerritory', to='game_analysis.Bonus')),
                ('connected_territories', models.ManyToManyField(related_name='_territory_connected_territories_+', to='game_analysis.Territory')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Map')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateOverriddenBonus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_value', models.SmallIntegerField()),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Bonus')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Template')),
            ],
            options={
                'unique_together': {('template', 'bonus')},
            },
        ),
        migrations.CreateModel(
            name='TemplateCardSetting',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_of_pieces', models.SmallIntegerField()),
                ('initial_pieces', models.SmallIntegerField()),
                ('min_pieces_per_turn', models.SmallIntegerField()),
                ('weight', models.FloatField()),
                ('mode', models.SmallIntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Card')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Template')),
            ],
            options={
                'unique_together': {('template', 'card')},
            },
        ),
        migrations.AddField(
            model_name='template',
            name='card_settings',
            field=models.ManyToManyField(through='game_analysis.TemplateCardSetting', to='game_analysis.Card'),
        ),
        migrations.AddField(
            model_name='template',
            name='fog_level',
            field=models.ForeignKey(default='Foggy', on_delete=django.db.models.deletion.CASCADE, to='game_analysis.FogLevel'),
        ),
        migrations.AddField(
            model_name='template',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Map'),
        ),
        migrations.AddField(
            model_name='template',
            name='overridden_bonuses',
            field=models.ManyToManyField(through='game_analysis.TemplateOverriddenBonus', to='game_analysis.Bonus'),
        ),
        migrations.CreateModel(
            name='PlayerAccount',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('games', models.ManyToManyField(through='game_analysis.Player', to='game_analysis.Game')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='end_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.PlayerStateType'),
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Game'),
        ),
        migrations.AddField(
            model_name='player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.PlayerAccount'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.OrderType'),
        ),
        migrations.AddField(
            model_name='order',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='game_analysis.Player'),
        ),
        migrations.AddField(
            model_name='order',
            name='primary_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game_analysis.Territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='secondary_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game_analysis.Territory'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_bonus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Bonus'),
        ),
        migrations.AddField(
            model_name='order',
            name='target_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game_analysis.Player'),
        ),
        migrations.AddField(
            model_name='order',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Turn'),
        ),
        migrations.AddField(
            model_name='game',
            name='ladder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Ladder'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='game_analysis.Player', to='game_analysis.PlayerAccount'),
        ),
        migrations.AddField(
            model_name='game',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Template'),
        ),
        migrations.AddField(
            model_name='bonusterritory',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Territory'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_analysis.Map'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='territories',
            field=models.ManyToManyField(through='game_analysis.BonusTerritory', to='game_analysis.Territory'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('turn', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bonusterritory',
            unique_together={('bonus', 'territory')},
        ),
    ]
