# Generated by Django 2.2.3 on 2019-08-04 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_analysis', '0002_auto_20190801_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='in_distribution_armies',
            new_name='initial_armies',
        ),
        migrations.AddField(
            model_name='templatecardsetting',
            name='duration',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='fog_level',
            field=models.ForeignKey(default='Foggy', on_delete=django.db.models.deletion.CASCADE, to='game_analysis.FogLevel'),
        ),
    ]
