# Generated by Django 2.2.3 on 2019-09-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analysis', '0002_initialize_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
