# Generated by Django 2.2.3 on 2019-09-19 23:57
import os.path

from django.db import connection, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_analysis', '0003_create_game_version_index'),
    ]

    def get_create_turn_state_view(apps, schema_editor):
        file_path = os.path.join(
            os.path.dirname(__file__),
            '../sql/create_turn_state_view.sql'
        )

        with open(file_path, 'r') as file:
            sql_statement = file.read()

        with connection.cursor() as c:
            c.execute(sql_statement)

    operations = [
         migrations.RunPython(get_create_turn_state_view),
    ]
