# Generated by Django 2.2.3 on 2019-08-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_analysis', '0003_order_card_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerState',
            new_name='PlayerStateType',
        ),
    ]
