# Generated by Django 2.2.3 on 2019-09-09 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_analysis', '0004_rename_player_state_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryClaim',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game_analysis.Order')),
                ('attack_transfer', models.CharField(default='AttackTransfer', max_length=15)),
                ('is_attack_teammates', models.BooleanField(default=False)),
                ('is_attack_by_percent', models.BooleanField(default=False)),
                ('is_attack', models.BooleanField()),
                ('is_successful', models.BooleanField()),
                ('attack_size', models.SmallIntegerField()),
                ('attacking_armies_killed', models.SmallIntegerField()),
                ('defending_armies_killed', models.SmallIntegerField()),
                ('offense_luck', models.FloatField()),
                ('defense_luck', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='attack_transfer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_attack_by_percent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_attack_teammates',
        ),
        migrations.DeleteModel(
            name='AttackResult',
        ),
    ]
