# Generated by Django 2.2.3 on 2019-09-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_analysis', '0005_auto_20190909_2253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='territorystate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='territorystate',
            name='player',
        ),
        migrations.RemoveField(
            model_name='territorystate',
            name='territory',
        ),
        migrations.RemoveField(
            model_name='territorystate',
            name='turn',
        ),
        migrations.AlterField(
            model_name='territoryclaim',
            name='attack_size',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='territoryclaim',
            name='attacking_armies_killed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='territoryclaim',
            name='defending_armies_killed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='territoryclaim',
            name='defense_luck',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='territoryclaim',
            name='is_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='territoryclaim',
            name='offense_luck',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CardState',
        ),
        migrations.DeleteModel(
            name='TerritoryState',
        ),
    ]
